apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: test
manifests:
  helm:
    releases:
      - name: test
        chartPath: curl-pod
      - name: test-service
        chartPath: none-cluster-ip-service
