apiVersion: v1
kind: Service
metadata:
  name: host-machine-svc
  labels:
    app: host-machine
spec:
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: host-machine-endpoints
  labels:
    app: host-machine
subsets:
  - addresses:
      - ip: 192.168.1.21